### ISSUE TITLE
error in generateUniqueId

### ISSUE THREAD

**Issue by segun-flexible** [seyi-js/vtpass-node#1]
its giving error
response_description: 'IMPROPER REQUEST ID: NOT PROPER DATE FORMAT – FIRST 8 CHARACTERS MUST BE DATE (TODAY’S DATE – YYYYMMDD)',

**Comment by seyi-js** [comment]
You can pass in the unique ID as into the methods( it seems vtpass has changed their method of generating ids, so i will have to make an update) till the issue is fixed. 
Thanks

**Comment by segun-flexible** [comment]
make the update, they are now requiring  the Id to be YYYY-MM-DD GMT+1

**Comment by seyi-js** [comment]
It has been resolved in the latest release.
